In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('https://storage.googleapis.com/additional-data/newCummulatedClean/new_CMaster_HPS_CDC_CPS_NYC_Vaccinated.csv')

/Users/dev/miniforge3/envs/ml4t/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3169: DtypeWarning: Columns (5,6) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [4]:
df.head()

,Unnamed: 0,YMFIPS_x,YEAR,MONTH,FIPS,STATE,STATE_CODE,TBIRTH_YEAR,EEDUC,THHLD_NUMPER,...,CDCCOUNT,REMPCT,people_vaccinated,people_vaccinated_per_hundred,people_fully_vaccinated,people_fully_vaccinated_per_hundred,ANXIOUS,WORRY,DOWN,cases_avg_per_100k
0,0,2021-9-01,2021,SEP,1.0,Alabama,AL,1941,7,1,...,44878.0,0.032,2583590.0,52.69,2089852.0,42.62,1,1,1,2148.73
1,1,2021-9-01,2021,SEP,1.0,Alabama,AL,1973,4,3,...,44878.0,0.032,2583590.0,52.69,2089852.0,42.62,4,1,1,2148.73
2,2,2021-9-13,2021,SEP,13.0,Georgia,GA,1970,4,1,...,58816.0,0.043,5828605.0,54.90,4823331.0,45.43,1,1,3,1772.88
3,3,2021-9-01,2021,SEP,1.0,Alabama,AL,1969,3,6,...,44878.0,0.032,2583590.0,52.69,2089852.0,42.62,3,3,1,2148.73
4,4,2021-9-01,2021,SEP,1.0,Alabama,AL,1977,4,3,...,44878.0,0.032,2583590.0,52.69,2089852.0,42.62,4,4,4,2148.73

In [5]:
new_df = pd.read_csv("https://storage.googleapis.com/additional-data/CummulatedClean_Nov22_with_lock/0_CMaster2_HPS_CDC_CPS_Vaccinated_with_lock.csv")

/Users/dev/miniforge3/envs/ml4t/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3169: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [6]:
new_df.head()

,Unnamed: 0,YMFIPS,YEAR,MONTH,FIPS,STATE,LOCATION,TBIRTH_YEAR,EEDUC,THHLD_NUMPER,...,MORTLMTH,MORTCONF,INCOME,REMPCT,CDCCOUNT,people_vaccinated,people_vaccinated_per_hundred,people_fully_vaccinated,people_fully_vaccinated_per_hundred,lockdown
0,0,2021-9-01,2021,SEP,1,AL,Alabama,1941,7,1,...,-88,-88,4,0.032,44878.0,2583590.0,52.69,2089852.0,42.62,0
1,1,2021-9-01,2021,SEP,1,AL,Alabama,1973,4,3,...,1,4,6,0.032,44878.0,2583590.0,52.69,2089852.0,42.62,0
2,2,2021-9-13,2021,SEP,13,GA,Georgia,1970,4,1,...,1,3,1,0.043,58816.0,5828605.0,54.90,4823331.0,45.43,0
3,3,2021-9-01,2021,SEP,1,AL,Alabama,1969,3,6,...,-88,-88,-88,0.032,44878.0,2583590.0,52.69,2089852.0,42.62,0
4,4,2021-9-01,2021,SEP,1,AL,Alabama,1977,4,3,...,-88,-88,-88,0.032,44878.0,2583590.0,52.69,2089852.0,42.62,0