In [86]:
import pandas as pd
import numpy as np
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [2]:
df_covid = pd.read_csv("us-counties.csv")

In [3]:
df_covid.head()

,date,geoid,county,state,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k
0,2020-01-21,USA-53061,Snohomish,Washington,1,0.14,0.02,0,0.0,0.0
1,2020-01-22,USA-53061,Snohomish,Washington,0,0.14,0.02,0,0.0,0.0
2,2020-01-23,USA-53061,Snohomish,Washington,0,0.14,0.02,0,0.0,0.0
3,2020-01-24,USA-53061,Snohomish,Washington,0,0.14,0.02,0,0.0,0.0
4,2020-01-24,USA-17031,Cook,Illinois,1,0.14,0.00,0,0.0,0.0

In [4]:
df_covid.describe()

,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k
count,1.774204e+06,1.774204e+06,1.753434e+06,1.774204e+06,1.774204e+06,1.753434e+06
mean,2.444017e+01,2.523847e+01,2.484046e+01,3.909049e-01,3.999916e-01,4.298328e-01
std,2.968251e+02,1.633520e+02,3.352340e+01,1.026638e+01,3.594971e+00,1.122688e+00
min,-1.239550e+05,0.000000e+00,0.000000e+00,-1.131700e+04,0.000000e+00,0.000000e+00
25%,0.000000e+00,8.300000e-01,4.040000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.000000e+00,3.710000e+00,1.271000e+01,0.000000e+00,0.000000e+00,0.000000e+00
75%,1.200000e+01,1.400000e+01,3.337000e+01,0.000000e+00,2.900000e-01,4.300000e-01
max,5.661000e+04,2.637233e+04,1.648350e+03,1.554000e+03,8.288600e+02,8.242000e+01

In [5]:
df_location = pd.read_csv("county_centers.csv")

In [6]:
df_location.head()

,fips,clon00,clat00,clon10,clat10,pclon00,pclat00,pclon10,pclat10
0,1001,-86.577176,32.523283,-86.644490,32.536382,-86.501832,32.500323,-86.494165,32.500389
1,1003,-87.748260,30.592781,-87.746067,30.659218,-87.760540,30.565383,-87.762381,30.548923
2,1005,-85.331312,31.856515,-85.405456,31.870670,-85.306746,31.847869,-85.310038,31.844036
3,1007,-87.123243,33.040054,-87.127148,33.015893,-87.127019,33.025947,-87.127659,33.030921
4,1009,-86.554768,33.978461,-86.567246,33.977448,-86.582617,33.962601,-86.591491,33.955243

In [7]:
df_location.describe()

,fips,clon00,clat00,clon10,clat10,pclon00,pclat00,pclon10,pclat10
count,3147.000000,3141.000000,3141.000000,3143.000000,3143.000000,3141.000000,3141.000000,3143.000000,3143.000000
mean,30370.300922,-92.252030,38.439020,-92.173302,38.454514,-92.251741,38.437457,-92.285805,38.450389
std,15184.666977,12.915532,5.281749,13.741422,5.306699,12.923385,5.279845,12.959277,5.300636
min,1001.000000,-172.454123,19.683885,-164.188912,19.597764,-167.880500,19.690126,-168.292885,19.672837
25%,18174.000000,-98.217441,34.715038,-98.222480,34.696827,-98.204061,34.719295,-98.224273,34.723433
50%,29175.000000,-90.373780,38.366222,-90.371770,38.373344,-90.334985,38.367247,-90.372418,38.372848
75%,45082.000000,-83.434400,41.785251,-83.425924,41.817127,-83.425062,41.809423,-83.433141,41.815946
max,56045.000000,-67.550334,70.599509,178.338813,69.449343,-67.452960,70.636549,-67.464919,70.522779

In [8]:
df_location.value_counts()

fips   clon00       clat00     clon10       clat10     pclon00      pclat00    pclon10      pclat10
1001   -86.577176   32.523283  -86.644490   32.536382  -86.501832   32.500323  -86.494165   32.500389    1
39095  -83.608466   41.649267  -83.468867   41.682321  -83.608547   41.654790  -83.615345   41.652803    1
39099  -80.706497   41.052558  -80.770396   41.010880  -80.694515   41.052213  -80.696308   41.049535    1
39101  -83.130561   40.583138  -83.172927   40.588208  -83.131442   40.582396  -83.129156   40.582060    1
39103  -81.872052   41.112580  -81.899566   41.116051  -81.842393   41.143580  -81.840120   41.144056    1
                                                                                                        ..
21123  -85.694210   37.528269  -85.697209   37.545518  -85.722089   37.544621  -85.723408   37.544796    1
21125  -84.083545   37.106679  -84.119395   37.113268  -84.089646   37.091772  -84.087834   37.091397    1
21127  -82.705282   38.075692  -82.738305   38.074459  -82.683785   38.075969  -82.681643   38.078995    1
21129  -83.697023   37.591061  -83.718497   37.605383  -83.702476   37.590107  -83.701692   37.591773    1
56045  -104.562398  43.879790  -104.570020  43.846213  -104.312710  43.901854  -104.312414  43.910214    1
Length: 3137, dtype: int64

# Adding retrieveing fips from geo id

In [9]:
def get_fips(geoid):
    
    id_list = geoid.split("-")
    fips = id_list[1]
    return fips

In [10]:
df_covid['fips'] = df_covid['geoid'].apply(lambda x: int(get_fips(x)))

In [11]:
df_covid.head()

,date,geoid,county,state,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k,fips
0,2020-01-21,USA-53061,Snohomish,Washington,1,0.14,0.02,0,0.0,0.0,53061
1,2020-01-22,USA-53061,Snohomish,Washington,0,0.14,0.02,0,0.0,0.0,53061
2,2020-01-23,USA-53061,Snohomish,Washington,0,0.14,0.02,0,0.0,0.0,53061
3,2020-01-24,USA-53061,Snohomish,Washington,0,0.14,0.02,0,0.0,0.0,53061
4,2020-01-24,USA-17031,Cook,Illinois,1,0.14,0.00,0,0.0,0.0,17031

# Retrieving required lat and long coordinates

In [12]:
df_loc = df_location[['fips', 'clon10', 'clat10']]

In [13]:
df_loc.head()

   fips     clon10     clat10
0  1001 -86.644490  32.536382
1  1003 -87.746067  30.659218
2  1005 -85.405456  31.870670
3  1007 -87.127148  33.015893
4  1009 -86.567246  33.977448

In [14]:
lon_dict = df_loc[['fips', 'clon10']].to_dict()

In [15]:
lon_dict = pd.Series(df_loc.clon10.values, index= df_loc.fips).to_dict()

In [16]:
lon_dict

{1001: -86.64449,
 1003: -87.746067,
 1005: -85.405456,
 1007: -87.127148,
 1009: -86.567246,
 1011: -85.717261,
 1013: -86.681969,
 1015: -85.822513,
 1017: -85.391812,
 1019: -85.654242,
 1021: -86.726627,
 1023: -88.248887,
 1025: -87.818624,
 1027: -85.862051,
 1029: -85.516109,
 1031: -85.989201,
 1033: -87.801457,
 1035: -86.992029,
 1037: -86.243482,
 1039: -86.448721,
 1041: -86.319222,
 1043: -86.869267,
 1045: -85.609476,
 1047: -87.114356,
 1049: -85.803992,
 1051: -86.142738,
 1053: -87.168429,
 1055: -86.03442,
 1057: -87.752049,
 1059: -87.842815,
 1061: -85.824346,
 1063: -87.9642,
 1065: -87.623061,
 1067: -85.239971,
 1069: -85.296398,
 1071: -85.9774,
 1073: -86.896536,
 1075: -88.087431,
 1077: -87.650997,
 1079: -87.321865,
 1081: -85.353048,
 1083: -86.981399,
 1085: -86.650586,
 1087: -85.692887,
 1089: -86.55108,
 1091: -87.791091,
 1093: -87.881551,
 1095: -86.321668,
 1097: -88.196568,
 1099: -87.383266,
 1101: -86.203831,
 1103: -86.846402,
 1105: -87.293827,
 1107: -88.096878,
 1109: -85.941997,
 1111: -85.464068,
 1113: -85.18698,
 1115: -86.315663,
 1117: -86.678104,
 1119: -88.200057,
 1121: -86.175805,
 1123: -85.799553,
 1125: -87.52286,
 1127: -87.301092,
 1129: -88.202078,
 1131: -87.302205,
 1133: -87.364147,
 2013: -161.950749,
 2016: 178.338813,
 2020: -149.274354,
 2050: -160.15335,
 2060: -156.986612,
 2068: -150.026719,
 2070: -158.602233,
 2090: -146.599867,
 2100: -135.578102,
 2105: -135.1851,
 2110: -134.178781,
 2122: -152.321973,
 2130: -131.106685,
 2150: -153.630911,
 2164: -156.705188,
 2170: -149.407974,
 2180: -164.188912,
 2185: -153.47283,
 2188: -160.021086,
 2195: -133.527996,
 2198: -132.875734,
 2201: nan,
 2220: -135.332624,
 2230: -135.335418,
 2232: nan,
 2240: -143.218628,
 2261: -145.023141,
 2270: -163.19095,
 2275: -132.040325,
 2280: nan,
 2282: -140.239593,
 2290: -151.576855,
 4001: -109.493747,
 4003: -109.75412,
 4005: -111.773728,
 4007: -110.81187,
 4009: -109.87831,
 4011: -109.242323,
 4012: -114.038793,
 4013: -112.495534,
 4015: -113.749689,
 4017: -110.320908,
 4019: -111.783018,
 4021: -111.367257,
 4023: -110.84519,
 4025: -112.573745,
 4027: -113.910905,
 5001: -91.376547,
 5003: -91.772267,
 5005: -92.330438,
 5007: -94.256187,
 5009: -93.079204,
 5011: -92.168164,
 5013: -92.513879,
 5015: -93.541663,
 5017: -91.297158,
 5019: -93.176205,
 5021: -90.418704,
 5023: -92.059974,
 5025: -92.188714,
 5027: -93.226901,
 5029: -92.689248,
 5031: -90.630411,
 5033: -94.236224,
 5035: -90.315331,
 5037: -90.773894,
 5039: -92.653999,
 5041: -91.244427,
 5043: -91.722778,
 5045: -92.324654,
 5047: -93.887672,
 5049: -91.819239,
 5051: -93.146915,
 5053: -92.423984,
 5055: -90.565241,
 5057: -93.665809,
 5059: -92.944147,
 5061: -93.990988,
 5063: -91.559942,
 5065: -91.913625,
 5067: -91.223178,
 5069: -91.930701,
 5071: -93.466322,
 5073: -93.611643,
 5075: -91.101153,
 5077: -90.779288,
 5079: -91.727624,
 5081: -94.229774,
 5083: -93.720563,
 5085: -91.894132,
 5087: -93.724053,
 5089: -92.678588,
 5091: -93.901509,
 5093: -90.052209,
 5095: -91.203314,
 5097: -93.664147,
 5099: -93.305072,
 5101: -93.215084,
 5103: -92.878418,
 5105: -92.926877,
 5107: -90.848386,
 5109: -93.658659,
 5111: -90.680595,
 5113: -94.230884,
 5115: -93.031535,
 5117: -91.557199,
 5119: -92.316515,
 5121: -91.028441,
 5123: -90.742199,
 5125: -92.674463,
 5127: -94.063641,
 5129: -92.699351,
 5131: -94.274989,
 5133: -94.24329,
 5135: -91.471069,
 5137: -92.140494,
 5139: -92.598145,
 5141: -92.515977,
 5143: -94.218417,
 5145: -91.753158,
 5147: -91.244418,
 5149: -93.408303,
 6001: -121.913304,
 6003: -119.798999,
 6005: -120.653856,
 6007: -121.601919,
 6009: -120.555115,
 6011: -122.237563,
 6013: -121.951543,
 6015: -123.980998,
 6017: -120.534398,
 6019: -119.655019,
 6021: -122.4017,
 6023: -123.925818,
 6025: -115.355395,
 6027: -117.403927,
 6029: -118.729506,
 6031: -119.81553,
 6033: -122.746757,
 6035: -120.629931,
 6037: -118.261862,
 6039: -119.749852,
 6041: -122.745974,
 6043: -119.91286,
 6045: -123.442881,
 6047: -120.722802,
 6049: -120.71837,
 6051: -118.875167,
 6053: -121.315573,
 6055: -122.325995,
 6057: -120.773446,
 6059: -117.777207,
 6061: -120.722718,
 6063: -120.829515,
 6065: -116.002239,
 6067: -121.340441,
 6069: -121.085296,
 6071: -116.181197,
 6073: -116.776117,
 6075: -123.032229,
 6077: -121.272237,
 6079: -120.44754,
 6081: -122.371542,
 6083: -120.038485,
 6085: -121.690622,
 6087: -122.007205,
 6089: -122.04355,
 6091: -120.521993,
 6093: -122.533287,
 6095: -121.939594,
 6097: -122.945194,
 6099: -121.002656,
 6101: -121.702758,
 6103: -122.232276,
 6105: -123.114404,
 6107: -118.780542,
 6109: -119.964708,
 6111: -119.133143,
 6113: -121.903178,
 6115: -121.34428,
 8001: -104.331872,
 8003: -105.788041,
 8005: -104.331733,
 8007: -107.050863,
 8009: -102.535457,
 8011: -103.077584,
 8013: -105.398382,
 8014: -105.052125,
 8015: -106.316972,
 8017: -102.604585,
 8019: -105.670791,
 8021: -106.176447,
 8023: -105.42894,
 8025: -103.787562,
 8027: -105.373515,
 8029: -107.864757,
 8031: -104.880625,
 8033: -108.530383,
 8035: -104.926199,
 8037: -106.692944,
 8039: -104.117928,
 8041: -104.527472,
 8043: -105.421438,
 8045: -107.90978,
 8047: -105.528947,
 8049: -106.095876,
 8051: -107.078108,
 8053: -107.383405,
 8055: -104.959928,
 8057: -106.329248,
 8059: -105.245601,
 8061: -102.75621,
 8063: -102.603023,
 8065: -106.349696,
 8067: -107.839718,
 8069: -105.482131,
 8071: -104.04411,
 8073: -103.507555,
 8075: -103.090464,
 8077: -108.461837,
 8079: -106.9323,
 8081: -108.204521,
 8083: -108.595786,
 8085: -108.263042,
 8087: -103.807092,
 8089: -103.72126,
 8091: -107.767133,
 8093: -105.717648,
 8095: -102.345105,
 8097: -106.915943,
 8099: -102.392161,
 8101: -104.489892,
 8103: -108.200685,
 8105: -106.453214,
 8107: -106.985288,
 8109: -106.246675,
 8111: -107.670257,
 8113: -108.427326,
 8115: -102.355358,
 8117: -106.137555,
 8119: -105.182552,
 8121: -103.209605,
 8123: -104.383649,
 8125: -102.422649,
 9001: -73.366757,
 9003: -72.732916,
 9005: -73.235428,
 9007: -72.524227,
 9009: -72.900204,
 9011: -72.103452,
 9013: -72.340977,
 9015: -71.990702,
 10001: -75.502982,
 10003: -75.644132,
 10005: -75.335495,
 11001: -77.017094,
 12001: -82.357221,
 12003: -82.302284,
 12005: -85.631348,
 12007: -82.166796,
 12009: -80.700384,
 12011: -80.476658,
 12013: -85.197915,
 12015: -81.940858,
 12017: -82.524796,
 12019: -81.858147,
 12021: -81.400884,
 12023: -82.623127,
 12027: -81.806253,
 12029: -83.195666,
 12031: -81.648113,
 12033: -87.33904,
 12035: -81.286362,
 12037: -84.799173,
 12039: -84.612783,
 12041: -82.795801,
 12043: -81.19082,
 12045: -85.256537,
 12047: -82.951049,
 12049: -81.82158,
 12051: -81.151584,
 12053: -82.464835,
 12055: -81.340921,
 12057: -82.349568,
 12059: -85.812959,
 12061: -80.574803,
 12063: -85.210374,
 12065: -83.890859,
 12067: -83.17851,
 12069: -81.712282,
 12071: -81.89225,
 12073: -84.2778,
 12075: -82.783482,
 12077: -84.86858,
 12079: -83.470437,
 12081: -82.365783,
 12083: -82.0431,
 12085: -80.398211,
 12086: -80.499045,
 12087: -81.206777,
 12089: -81.764929,
 12091: -86.594194,
 12093: -80.887388,
 12095: -81.323295,
 12097: -81.139312,
 12099: -80.448673,
 12101: -82.455707,
 12103: -82.739518,
 12105: -81.692783,
 12107: -81.740894,
 12109: -81.383914,
 12111: -80.443364,
 12113: -87.014255,
 12115: -82.365835,
 12117: -81.13198,
 12119: -82.074715,
 12121: -82.992754,
 12123: -83.616417,
 12125: -82.366918,
 12127: -81.161813,
 12129: -84.375136,
 12131: -86.176614,
 12133: -85.662797,
 13001: -82.290103,
 13003: -82.883614,
 13005: -82.387859,
 13007: -84.454857,
 13009: -83.255362,
 13011: -83.498441,
 13013: -83.712303,
 13015: -84.838188,
 13017: -83.14719,
 13019: -83.231906,
 13021: -83.694193,
 13023: -83.331717,
 13025: -81.982978,
 13027: -83.588971,
 13029: -81.438543,
 13031: -81.74381,
 13033: -82.00389,
 13035: -83.958221,
 13037: -84.62629,
 13039: -81.636516,
 13043: -82.071446,
 13045: -85.080527,
 13047: -85.137353,
 13049: -82.139644,
 13051: -81.091768,
 13053: -84.788021,
 13055: -85.345289,
 13057: -84.475057,
 13059: -83.36713,
 13061: -84.992583,
 13063: -84.412977,
 13065: -82.702614,
 13067: -84.574166,
 13069: -82.844938,
 13071: -83.769741,
 13073: -82.251342,
 13075: -83.429551,
 13077: -84.762138,
 13079: -83.979182,
 13081: -83.753338,
 13083: -85.506201,
 13085: -84.173284,
 13087: -84.577744,
 13089: -84.226343,
 13091: -83.156818,
 13093: -83.807167,
 13095: -84.214444,
 13097: -84.765944,
 13099: -84.906723,
 13101: -82.836132,
 13103: -81.343337,
 13105: -82.842057,
 13107: -82.299763,
 13109: -81.887618,
 13111: -84.319287,
 13113: -84.493941,
 13115: -85.21373,
 13117: -84.127336,
 13119: -83.22729,
 13121: -84.468182,
 13123: -84.453984,
 13125: -82.606913,
 13127: -81.496517,
 13129: -84.873862,
 13131: -84.244772,
 13133: -83.167103,
 13135: -84.022938,
 13137: -83.526406,
 13139: -83.818497,
 13141: -83.000465,
 13143: -85.220062,
 13145: -84.912432,
 13147: -82.96329,
 13149: -85.139594,
 13151: -84.15444,
 13153: -83.662856,
 13155: -83.277037,
 13157: -83.565133,
 13159: -83.687892,
 13161: -82.636825,
 13163: -82.41905,
 13165: -81.971524,
 13167: -82.661354,
 13169: -83.562339,
 13171: -84.146721,
 13173: -83.063164,
 13175: -82.926317,
 13177: -84.146681,
 13179: -81.457969,
 13181: -82.448299,
 13183: -81.74287,
 13185: -83.268967,
 13187: -83.998827,
 13189: -82.473188,
 13191: -81.370199,
 13193: -84.052162,
 13195: -83.203637,
 13197: -84.529561,
 13199: -84.663279,
 13201: -84.730386,
 13205: -84.192407,
 13207: -83.922938,
 13209: -82.533349,
 13211: -83.492324,
 13213: -84.73799,
 13215: -84.874946,
 13217: -83.855189,
 13219: -83.437728,
 13221: -83.074081,
 13223: -84.866979,
 13225: -83.831978,
 13227: -84.490256,
 13229: -82.210427,
 13231: -84.386627,
 13233: -85.186826,
 13235: -83.481855,
 13237: -83.37179,
 13239: -85.009317,
 13241: -83.404735,
 13243: -84.752311,
 13245: -82.074998,
 13247: -84.02637,
 13249: -84.322724,
 13251: -81.617585,
 13253: -84.867592,
 13255: -84.286067,
 13257: -83.290216,
 13259: -84.834912,
 13261: -84.204283,
 13263: -84.530029,
 13265: -82.875208,
 13267: -82.059208,
 13269: -84.251426,
 13271: -82.931062,
 13273: -84.439446,
 13275: -83.919783,
 13277: -83.525931,
 13279: -82.332071,
 13281: -83.732158,
 13283: -82.570882,
 13285: -85.02836,
 13287: -83.628566,
 13289: -83.425879,
 13291: -83.989573,
 13293: -84.292281,
 13295: -85.305385,
 13297: -83.734215,
 13299: -82.421507,
 13301: -82.688012,
 13303: -82.798112,
 13305: -81.912376,
 13307: -84.553218,
 13309: -82.738701,
 13311: -83.743713,
 13313: -84.968541,
 13315: -83.438262,
 13317: -82.747922,
 13319: -83.175587,
 13321: -83.84996,
 15001: -155.502443,
 15003: -158.201976,
 15005: -156.97401,
 15007: -159.705965,
 15009: -156.60155,
 16001: -116.244456,
 16003: -116.431873,
 16005: -112.228986,
 16007: -111.327445,
 16009: -116.633541,
 16011: -112.399206,
 16013: -113.95529,
 16015: -115.71511,
 16017: -116.59694,
 16019: -111.621878,
 16021: -116.524619,
 16023: -113.177627,
 16025: -114.804427,
 16027: -116.708527,
 16029: -111.544171,
 16031: -113.605498,
 16033: -112.36112,
 16035: -115.6535,
 16037: -114.252251,
 16039: -115.470751,
 16041: -111.822955,
 16043: -111.484429,
 16045: -116.398784,
 16047: -114.82142,
 16049: -115.467376,
 16051: -112.318588,
 16053: -114.263009,
 16055: -116.694918,
 16057: -116.730974,
 16059: -113.887841,
 16061: -116.42376,
 16063: -114.153899,
 16065: -111.65655,
 16067: -113.64001,
 16069: -116.760903,
 16071: -112.520465,
 16073: -116.142655,
 16075: -116.748655,
 16077: -112.844407,
 16079: -115.885092,
 16081: -111.211765,
 16083: -114.665639,
 16085: -115.637875,
 16087: -116.79783,
 17001: -91.194961,
 17003: -89.349506,
 17005: -89.436592,
 17007: -88.824295,
 17009: -90.750309,
 17011: -89.528377,
 17013: -90.666295,
 17015: -89.926485,
 17017: -90.245704,
 17019: -88.197201,
 17021: -89.279593,
 17023: -87.791687,
 17025: -88.483789,
 17027: -89.423136,
 17029: -88.220782,
 17031: -87.645455,
 17033: -87.757172,
 17035: -88.240619,
 17037: -88.768991,
 17039: -88.901853,
 17041: -88.222866,
 17043: -88.086038,
 17045: -87.74711,
 17047: -88.047941,
 17049: -88.592786,
 17051: -89.017923,
 17053: -88.224746,
 17055: -88.926246,
 17057: -90.206793,
 17059: -88.227964,
 17061: -90.387757,
 17063: -88.401054,
 17065: -88.539005,
 17067: -91.167987,
 17069: -88.266148,
 17071: -90.93848,
 17073: -90.130838,
 17075: -87.833601,
 17077: -89.381212,
 17079: -88.150763,
 17081: -88.92421,
 17083: -90.361365,
 17085: -90.21147,
 17087: -88.882962,
 17089: -88.42804,
 17091: -87.861125,
 17093: -88.430626,
 17095: -90.213761,
 17097: -87.436118,
 17099: -88.885931,
 17101: -87.730221,
 17103: -89.299351,
 17105: -88.552852,
 17107: -89.365308,
 17109: -90.677579,
 17111: -88.452245,
 17113: -88.844539,
 17115: -88.961529,
 17117: -89.926344,
 17119: -89.900195,
 17121: -88.920221,
 17123: -89.342371,
 17125: -89.913575,
 17127: -88.705658,
 17129: -89.794133,
 17131: -90.741433,
 17133: -90.179078,
 17135: -89.478007,
 17137: -90.202277,
 17139: -88.625726,
 17141: -89.320176,
 17143: -89.767358,
 17145: -89.368487,
 17147: -88.592328,
 17149: -90.889034,
 17151: -88.542374,
 17153: -89.127755,
 17155: -89.298386,
 17157: -89.82121,
 17159: -88.085698,
 17161: -90.572203,
 17163: -89.928546,
 17165: -88.545031,
 17167: -89.662311,
 17169: -90.613464,
 17171: -90.477759,
 17173: -88.798862,
 17175: -89.797411,
 17177: -89.665994,
 17179: -89.51626,
 17181: -89.252875,
 17183: -87.726771,
 17185: -87.839167,
 17187: -90.620223,
 17189: -89.417187,
 17191: -88.432129,
 17193: -88.178585,
 17195: -89.910957,
 17197: -87.978456,
 17199: -88.930018,
 17201: -89.161205,
 17203: -89.210301,
 18001: -84.93613,
 18003: -85.07223,
 18005: -85.897999,
 18007: -87.315479,
 18009: -85.32373,
 18011: -86.469014,
 18013: -86.23941,
 18015: -86.565141,
 18017: -86.355168,
 18019: -85.711122,
 18021: -87.115837,
 18023: -86.477567,
 18025: -86.440871,
 18027: -87.076988,
 18029: -84.97346,
 18031: -85.499831,
 18033: -85.000185,
 18035: -85.398856,
 18037: -86.873385,
 18039: -85.863986,
 18041: -85.185032,
 18043: -85.911474,
 18045: -87.234806,
 18047: -85.066964,
 18049: -86.265006,
 18051: -87.580566,
 18053: -85.654946,
 18055: -87.005245,
 18057: -86.020586,
 18059: -85.772904,
 18061: -86.103681,
 18063: -86.510286,
 18065: -85.397338,
 18067: -86.114118,
 18069: -85.478597,
 18071: -86.042516,
 18073: -87.118814,
 18075: -85.00338,
 18077: -85.44009,
 18079: -85.628111,
 18081: -86.0946,
 18083: -87.420182,
 18085: -85.861575,
 18087: -85.426302,
 18089: -87.374337,
 18091: -86.744729,
 18093: -86.48782,
 18095: -85.722454,
 18097: -86.135794,
 18099: -86.269036,
 18101: -86.801847,
 18103: -86.044258,
 18105: -86.523325,
 18107: -86.892715,
 18109: -86.447457,
 18111: -87.402172,
 18113: -85.41785,
 18115: -84.964299,
 18117: -86.489257,
 18119: -86.838845,
 18121: -87.19695,
 18123: -86.62654,
 18125: -87.232532,
 18127: -87.071308,
 18129: -87.868653,
 18131: -86.692538,
 18133: -86.853325,
 18135: -85.005004,
 18137: -85.260541,
 18139: -85.466526,
 18141: -86.288159,
 18143: -85.751898,
 18145: -85.792174,
 18147: -87.010645,
 18149: -86.64757,
 18151: -85.002467,
 18153: -87.415843,
 18155: -85.029679,
 18157: -86.893943,
 18159: -86.056207,
 18161: -84.925152,
 18163: -87.586166,
 18165: -87.462071,
 18167: -87.390375,
 18169: -85.795175,
 18171: -87.375847,
 18173: -87.272023,
 18175: -86.104751,
 18177: -85.006735,
 18179: -85.212974,
 18181: -86.864293,
 18183: -85.501892,
 19001: -94.478164,
 19003: -94.696906,
 19005: -91.382751,
 19007: -92.870345,
 19009: -94.904312,
 19011: -92.05763,
 19013: -92.306059,
 19015: -93.939138,
 19017: -92.327586,
 19019: -91.838666,
 19021: -95.141433,
 19023: -92.780066,
 19025: -94.643683,
 19027: -94.867647,
 19029: -94.933302,
 19031: -91.13219,
 19033: -93.251266,
 19035: -95.633262,
 19037: -92.31721,
 19039: -93.784096,
 19041: -95.149726,
 19043: -91.323511,
 19045: -90.534243,
 19047: -95.38909,
 19049: -94.040707,
 19051: -92.410345,
 19053: -93.78458,
 19055: -91.359442,
 19057: -91.186925,
 19059: -95.196057,
 19061: -90.878771,
 19063: -94.66937,
 19065: -91.839373,
 19067: -92.787367,
 19069: -93.271425,
 19071: -95.599516,
 19073: -94.388703,
 19075: -92.790261,
 19077: -94.501272,
 19079: -93.709198,
 19081: -93.743697,
 19083: -93.241081,
 19085: -95.827149,
 19087: -91.54427,
 19089: -92.321908,
 19091: -94.202775,
 19093: -95.507421,
 19095: -92.059123,
 19097: -90.574596,
 19099: -93.052971,
 19101: -91.967137,
 19103: -91.588812,
 19105: -91.116914,
 19107: -92.167721,
 19109: -94.213983,
 19111: -91.477157,
 19113: -91.597674,
 19115: -91.256994,
 19117: -93.331467,
 19119: -96.207201,
 19121: -94.015184,
 19123: -92.636366,
 19125: -93.093849,
 19127: -92.981452,
 19129: -95.619101,
 19131: -92.784466,
 19133: -95.956566,
 19135: -92.869642,
 19137: -95.15779,
 19139: -91.118699,
 19141: -95.625624,
 19143: -95.633788,
 19145: -95.14429,
 19147: -94.667296,
 19149: -96.215864,
 19151: -94.678279,
 19153: -93.56972,
 19155: -95.544905,
 19157: -92.522882,
 19159: -94.244251,
 19161: -95.105224,
 19163: -90.62229,
 19165: -95.308917,
 19167: -96.177929,
 19169: -93.466093,
 19171: -92.529411,
 19173: -94.697108,
 19175: -94.245091,
 19177: -91.952943,
 19179: -92.409482,
 19181: -93.564366,
 19183: -91.725052,
 19185: -93.332613,
 19187: -94.179156,
 19189: -93.743488,
 19191: -91.850788,
 19193: -96.053296,
 19195: -93.248533,
 19197: -93.734735,
 20001: -95.300945,
 20003: -95.292046,
 20005: -95.313397,
 20007: -98.685052,
 20009: -98.767837,
 20011: -94.850928,
 20013: -95.569905,
 20015: -96.838762,
 20017: -96.594064,
 20019: -96.245396,
 20021: -94.845698,
 20023: -101.727302,
 20025: -99.813869,
 20027: -97.168853,
 20029: -97.64139,
 20031: -95.729137,
 20033: -99.254089,
 20035: -96.837247,
 20037: -94.853941,
 20039: -100.459708,
 20041: -97.157943,
 20043: -95.147225,
 20045: -95.290529,
 20047: -99.304746,
 20049: -96.244642,
 20051: -99.317329,
 20053: -98.205355,
 20055: -100.739929,
 20057: -99.884734,
 20059: -95.278962,
 20061: -96.768038,
 20063: -100.48736,
 20065: -99.880952,
 20067: -101.299362,
 20069: -100.451716,
 20071: -101.805984,
 20073: -96.242232,
 20075: -101.793689,
 20077: -98.06659,
 20079: -97.436706,
 20081: -100.876869,
 20083: -99.898407,
 20085: -95.794509,
 20087: -95.375314,
 20089: -98.222584,
 20091: -94.82233,
 20093: -101.308136,
 20095: -98.144529,
 20097: -99.286539,
 20099: -95.297473,
 20101: -100.466185,
 20103: -95.038977,
 20105: -98.214265,
 20107: -94.844932,
 20109: -101.157407,
 20111: -96.161589,
 20113: -97.647489,
 20115: -97.102771,
 20117: -96.521243,
 20119: -100.360094,
 20121: -94.832963,
 20123: -98.207362,
 20125: -95.742403,
 20127: -96.644905,
 20129: -101.809516,
 20131: -96.005381,
 20133: -95.315683,
 20135: -99.908745,
 20137: -99.899235,
 20139: -95.727275,
 20141: -98.767876,
 20143: -97.654802,
 20145: -99.232154,
 20147: -99.34215,
 20149: -96.337113,
 20151: -98.74012,
 20153: -101.076738,
 20155: -98.078346,
 20157: -97.650921,
 20159: -98.201415,
 20161: -96.727489,
 20163: -99.324492,
 20165: -99.309183,
 20167: -98.765638,
 20169: -97.650153,
 20171: -100.90636,
 20173: -97.459451,
 20175: -100.854741,
 20177: -95.755664,
 20179: -100.441206,
 20181: -101.719859,
 20183: -98.785429,
 20185: -98.719889,
 20187: -101.789383,
 20189: -101.315796,
 20191: -97.493349,
 20193: -101.083438,
 20195: -99.865423,
 20197: -96.201262,
 20199: -101.771103,
 20201: -97.095611,
 20203: -101.347434,
 20205: -95.745175,
 20207: -95.757553,
 20209: -94.763087,
 21001: -85.2814,
 21003: -86.192458,
 21005: -84.986417,
 21007: -89.009178,
 ...}

In [25]:
lon_dict[36998] = 74.0060

In [17]:
lat_dict = pd.Series(df_loc.clat10.values, index= df_loc.fips).to_dict()

In [26]:
lat_dict

{1001: 32.536382,
 1003: 30.659218,
 1005: 31.87067,
 1007: 33.015893,
 1009: 33.977448,
 1011: 32.101759,
 1013: 31.751667,
 1015: 33.771706,
 1017: 32.917943,
 1019: 34.069515,
 1021: 32.854059,
 1023: 31.991008,
 1025: 31.685521,
 1027: 33.267809,
 1029: 33.671981,
 1031: 31.402183,
 1033: 34.703112,
 1035: 31.428292,
 1037: 32.931445,
 1039: 31.243987,
 1041: 31.732826,
 1043: 34.131923,
 1045: 31.430654,
 1047: 32.33354,
 1049: 34.460929,
 1051: 32.597229,
 1053: 31.121747,
 1055: 34.047638,
 1057: 33.732249,
 1059: 34.441988,
 1061: 31.090866,
 1063: 32.844497,
 1065: 32.752796,
 1067: 31.516978,
 1069: 31.158193,
 1071: 34.763522,
 1073: 33.553444,
 1075: 33.787085,
 1077: 34.904122,
 1079: 34.529776,
 1081: 32.604064,
 1083: 34.810239,
 1085: 32.147888,
 1087: 32.387027,
 1089: 34.764238,
 1091: 32.247591,
 1093: 34.138219,
 1095: 34.309564,
 1097: 30.684573,
 1099: 31.580332,
 1101: 32.20365,
 1103: 34.454484,
 1105: 32.639005,
 1107: 33.296808,
 1109: 31.798726,
 1111: 33.296475,
 1113: 32.289811,
 1115: 33.712963,
 1117: 33.262937,
 1119: 32.597481,
 1121: 33.369277,
 1123: 32.863369,
 1125: 33.290202,
 1127: 33.791571,
 1129: 31.406974,
 1131: 31.99033,
 1133: 34.155888,
 2013: 55.243722,
 2016: 51.959447,
 2020: 61.177549,
 2050: 60.928916,
 2060: 58.731372,
 2068: 63.682732,
 2070: 59.824816,
 2090: 64.690832,
 2100: 59.099905,
 2105: 58.076434,
 2110: 58.3727,
 2122: 60.366373,
 2130: 55.449938,
 2150: 57.553611,
 2164: 58.205065,
 2170: 62.182174,
 2180: 64.783686,
 2185: 69.449343,
 2188: 67.005066,
 2195: 56.639612,
 2198: 55.415683,
 2201: nan,
 2220: 57.142508,
 2230: 59.575097,
 2232: nan,
 2240: 63.864997,
 2261: 61.34984,
 2270: 62.283174,
 2275: 56.279121,
 2280: nan,
 2282: 59.999083,
 2290: 65.376131,
 4001: 35.385845,
 4003: 31.881793,
 4005: 35.829692,
 4007: 33.789618,
 4009: 32.931828,
 4011: 33.238872,
 4012: 33.727625,
 4013: 33.346541,
 4015: 35.717705,
 4017: 35.390934,
 4019: 32.128237,
 4021: 32.91891,
 4023: 31.525904,
 4025: 34.630044,
 4027: 32.773942,
 5001: 34.289573,
 5003: 33.190835,
 5005: 36.28071,
 5007: 36.337825,
 5009: 36.304308,
 5011: 33.463819,
 5013: 33.56046,
 5015: 36.337774,
 5017: 33.267139,
 5019: 34.053312,
 5021: 36.367302,
 5023: 35.566288,
 5025: 33.893201,
 5027: 33.21507,
 5029: 35.265702,
 5031: 35.828268,
 5033: 35.583041,
 5035: 35.211878,
 5037: 35.291259,
 5039: 33.967823,
 5041: 33.828748,
 5043: 33.587242,
 5045: 35.146356,
 5047: 35.508573,
 5049: 36.383443,
 5051: 34.578861,
 5053: 34.288063,
 5055: 36.119922,
 5057: 33.728611,
 5059: 34.315177,
 5061: 34.083179,
 5063: 35.737499,
 5065: 36.094879,
 5067: 35.596605,
 5069: 34.277695,
 5071: 35.573359,
 5073: 33.24066,
 5075: 36.041098,
 5077: 34.77975,
 5079: 33.957665,
 5081: 33.699497,
 5083: 35.218549,
 5085: 34.755114,
 5087: 36.012545,
 5089: 36.266656,
 5091: 33.305505,
 5093: 35.766943,
 5095: 34.679513,
 5097: 34.545652,
 5099: 33.666699,
 5101: 35.910062,
 5103: 33.591158,
 5105: 34.946363,
 5107: 34.425842,
 5109: 34.158191,
 5111: 35.568981,
 5113: 34.490915,
 5115: 35.455297,
 5117: 34.828225,
 5119: 34.773988,
 5121: 36.341298,
 5123: 35.014438,
 5125: 34.648525,
 5127: 34.858869,
 5129: 35.90966,
 5131: 35.196981,
 5133: 33.994608,
 5135: 36.173399,
 5137: 35.856989,
 5139: 33.168219,
 5141: 35.582959,
 5143: 35.971209,
 5145: 35.254722,
 5147: 35.189071,
 5149: 34.997713,
 6001: 37.648081,
 6003: 38.61761,
 6005: 38.44355,
 6007: 39.665959,
 6009: 38.187844,
 6011: 39.177739,
 6013: 37.919479,
 6015: 41.749903,
 6017: 38.785532,
 6019: 36.761006,
 6021: 39.602546,
 6023: 40.706673,
 6025: 33.040816,
 6027: 36.561977,
 6029: 35.346629,
 6031: 36.072478,
 6033: 39.094802,
 6035: 40.721089,
 6037: 34.196398,
 6039: 37.210039,
 6041: 38.051817,
 6043: 37.570033,
 6045: 39.432388,
 6047: 37.194806,
 6049: 41.592918,
 6051: 37.915836,
 6053: 36.240107,
 6055: 38.507351,
 6057: 39.295191,
 6059: 33.675687,
 6061: 39.062032,
 6063: 39.99517,
 6065: 33.729828,
 6067: 38.450011,
 6069: 36.610702,
 6071: 34.85722,
 6073: 33.023604,
 6075: 37.727239,
 6077: 37.935034,
 6079: 35.385227,
 6081: 37.414664,
 6083: 34.537378,
 6085: 37.220777,
 6087: 37.012488,
 6089: 40.760521,
 6091: 39.576925,
 6093: 41.587986,
 6095: 38.267226,
 6097: 38.532574,
 6099: 37.562384,
 6101: 39.035257,
 6103: 40.126156,
 6105: 40.647724,
 6107: 36.230453,
 6109: 38.021451,
 6111: 34.358741,
 6113: 38.679268,
 6115: 39.270026,
 8001: 39.874325,
 8003: 37.568442,
 8005: 39.644632,
 8007: 37.202395,
 8009: 37.303144,
 8011: 37.931891,
 8013: 40.094826,
 8014: 39.953382,
 8015: 38.738246,
 8017: 38.835386,
 8019: 39.689403,
 8021: 37.213406,
 8023: 37.277547,
 8025: 38.321956,
 8027: 38.101994,
 8029: 38.861756,
 8031: 39.761849,
 8033: 37.747602,
 8035: 39.326435,
 8037: 39.630638,
 8039: 39.310817,
 8041: 38.827383,
 8043: 38.455658,
 8045: 39.599352,
 8047: 39.861082,
 8049: 40.123289,
 8051: 38.669679,
 8053: 37.811625,
 8055: 37.687815,
 8057: 40.663432,
 8059: 39.58646,
 8061: 38.388466,
 8063: 39.30534,
 8065: 39.204316,
 8067: 37.287367,
 8069: 40.663091,
 8071: 37.318831,
 8073: 38.99374,
 8075: 40.728091,
 8077: 39.019492,
 8079: 37.651478,
 8081: 40.573984,
 8083: 37.338025,
 8085: 38.413427,
 8087: 40.262353,
 8089: 37.88417,
 8091: 38.1506,
 8093: 39.118914,
 8095: 40.594712,
 8097: 39.217533,
 8099: 37.958181,
 8101: 38.170658,
 8103: 39.972606,
 8105: 37.485763,
 8107: 40.48316,
 8109: 38.033952,
 8111: 37.781074,
 8113: 38.009374,
 8115: 40.871568,
 8117: 39.621023,
 8119: 38.871994,
 8121: 39.965413,
 8123: 40.555794,
 8125: 40.000631,
 9001: 41.228103,
 9003: 41.806053,
 9005: 41.791897,
 9007: 41.434525,
 9009: 41.349717,
 9011: 41.47863,
 9013: 41.858076,
 9015: 41.824999,
 10001: 39.097088,
 10003: 39.575915,
 10005: 38.677511,
 11001: 38.904149,
 12001: 29.67574,
 12003: 30.324442,
 12005: 30.237563,
 12007: 29.946934,
 12009: 28.298275,
 12011: 26.19352,
 12013: 30.388801,
 12015: 26.868826,
 12017: 28.843628,
 12019: 29.987115,
 12021: 26.118713,
 12023: 30.221305,
 12027: 27.190581,
 12029: 29.580899,
 12031: 30.335245,
 12033: 30.611664,
 12035: 29.474894,
 12037: 29.810176,
 12039: 30.579169,
 12041: 29.723456,
 12043: 26.95481,
 12045: 29.907257,
 12047: 30.491102,
 12049: 27.492846,
 12051: 26.53934,
 12053: 28.567911,
 12055: 27.342627,
 12057: 27.90659,
 12059: 30.866222,
 12061: 27.700638,
 12063: 30.787812,
 12065: 30.424558,
 12067: 29.990066,
 12069: 28.764113,
 12071: 26.552134,
 12073: 30.45931,
 12075: 29.284409,
 12077: 30.259849,
 12079: 30.447228,
 12081: 27.481386,
 12083: 29.202805,
 12085: 27.079954,
 12086: 25.610494,
 12087: 25.601043,
 12089: 30.605926,
 12091: 30.665858,
 12093: 27.385592,
 12095: 28.514435,
 12097: 28.059027,
 12099: 26.645763,
 12101: 28.302024,
 12103: 27.903122,
 12105: 27.953115,
 12107: 29.606006,
 12109: 29.890593,
 12111: 27.380775,
 12113: 30.703633,
 12115: 27.184386,
 12117: 28.690079,
 12119: 28.714294,
 12121: 30.189244,
 12123: 30.016943,
 12125: 30.05428,
 12127: 29.057617,
 12129: 30.140378,
 12131: 30.631211,
 12133: 30.602217,
 13001: 31.739712,
 13003: 31.300562,
 13005: 31.563327,
 13007: 31.319622,
 13009: 33.059532,
 13011: 34.351922,
 13013: 33.992009,
 13015: 34.240917,
 13017: 31.740775,
 13019: 31.274308,
 13021: 32.808844,
 13023: 32.435403,
 13025: 31.197334,
 13027: 30.833696,
 13029: 32.017969,
 13031: 32.393408,
 13033: 33.063736,
 13035: 33.290355,
 13037: 31.521279,
 13039: 30.916358,
 13043: 32.403986,
 13045: 33.582237,
 13047: 34.899393,
 13049: 30.779904,
 13051: 31.974755,
 13053: 32.347445,
 13055: 34.474178,
 13057: 34.244317,
 13059: 33.952234,
 13061: 31.619831,
 13063: 33.552242,
 13065: 30.917653,
 13067: 33.93994,
 13069: 31.549245,
 13071: 31.189758,
 13073: 33.550556,
 13075: 31.152935,
 13077: 33.352897,
 13079: 32.709446,
 13081: 31.914753,
 13083: 34.852424,
 13085: 34.442842,
 13087: 30.877961,
 13089: 33.770661,
 13091: 32.160656,
 13093: 32.151995,
 13095: 31.535068,
 13097: 33.699317,
 13099: 31.324191,
 13101: 30.7085,
 13103: 32.361711,
 13105: 34.115017,
 13107: 32.5911,
 13109: 32.151902,
 13111: 34.863837,
 13113: 33.412717,
 13115: 34.263677,
 13117: 34.225143,
 13119: 34.375155,
 13121: 33.790034,
 13123: 34.690541,
 13125: 33.227491,
 13127: 31.212746,
 13129: 34.509667,
 13131: 30.875863,
 13133: 33.576836,
 13135: 33.959101,
 13137: 34.635108,
 13139: 34.317588,
 13141: 33.26922,
 13143: 33.795165,
 13145: 32.731549,
 13147: 34.348733,
 13149: 33.290968,
 13151: 33.452881,
 13153: 32.458381,
 13155: 31.604306,
 13157: 34.134157,
 13159: 33.314905,
 13161: 31.811615,
 13163: 33.051874,
 13165: 32.794563,
 13167: 32.689831,
 13169: 33.020226,
 13171: 33.07446,
 13173: 31.038197,
 13175: 32.39322,
 13177: 31.818419,
 13179: 31.807244,
 13181: 33.792151,
 13183: 31.749563,
 13185: 30.83368,
 13187: 34.568149,
 13189: 33.482464,
 13191: 31.482978,
 13193: 32.366216,
 13195: 34.128485,
 13197: 32.359538,
 13199: 33.03022,
 13201: 31.162908,
 13205: 31.22894,
 13207: 33.017435,
 13209: 32.172108,
 13211: 33.593732,
 13213: 34.797097,
 13215: 32.510197,
 13217: 33.544045,
 13219: 33.834125,
 13221: 33.866806,
 13223: 33.920903,
 13225: 32.571324,
 13227: 34.456621,
 13229: 31.353988,
 13231: 33.090768,
 13233: 33.995961,
 13235: 32.238794,
 13237: 33.32106,
 13239: 31.861487,
 13241: 34.883026,
 13243: 31.762651,
 13245: 33.361487,
 13247: 33.652081,
 13249: 32.263441,
 13251: 32.744751,
 13253: 30.933894,
 13255: 33.262389,
 13257: 34.552914,
 13259: 32.073225,
 13261: 32.042203,
 13263: 32.704603,
 13265: 33.559314,
 13267: 32.043768,
 13269: 32.554667,
 13271: 31.913639,
 13273: 31.777191,
 13275: 30.864616,
 13277: 31.457003,
 13279: 32.126698,
 13281: 34.90265,
 13283: 32.409586,
 13285: 33.034482,
 13287: 31.718232,
 13289: 32.665847,
 13291: 34.83377,
 13293: 32.881837,
 13295: 34.735827,
 13297: 33.782648,
 13299: 31.050881,
 13301: 33.419169,
 13303: 32.971848,
 13305: 31.547845,
 13307: 32.046554,
 13309: 32.109276,
 13311: 34.643677,
 13313: 34.801726,
 13315: 31.962717,
 13317: 33.77904,
 13319: 32.804321,
 13321: 31.551773,
 15001: 19.597764,
 15003: 21.461364,
 15005: 21.218764,
 15007: 22.012038,
 15009: 20.855931,
 16001: 43.447861,
 16003: 44.884583,
 16005: 42.692938,
 16007: 42.285833,
 16009: 47.218451,
 16011: 43.216357,
 16013: 43.394482,
 16015: 43.987275,
 16017: 48.312512,
 16019: 43.395171,
 16021: 48.773065,
 16023: 43.6851,
 16025: 43.463396,
 16027: 43.623051,
 16029: 42.786273,
 16031: 42.288635,
 16033: 44.286251,
 16035: 46.67257,
 16037: 44.273341,
 16039: 43.394826,
 16041: 42.173589,
 16043: 44.218091,
 16045: 44.061473,
 16047: 42.973185,
 16049: 45.849237,
 16051: 43.796965,
 16053: 42.691171,
 16055: 47.677113,
 16057: 46.81892,
 16059: 44.928789,
 16061: 46.236328,
 16063: 42.986181,
 16065: 43.789709,
 16067: 42.856937,
 16069: 46.333766,
 16071: 42.18389,
 16073: 42.593063,
 16075: 44.00274,
 16077: 42.694126,
 16079: 47.347694,
 16081: 43.760994,
 16083: 42.352309,
 16085: 44.771532,
 16087: 44.448213,
 17001: 39.986052,
 17003: 37.183683,
 17005: 38.885924,
 17007: 42.318983,
 17009: 39.962069,
 17011: 41.401304,
 17013: 39.164262,
 17015: 42.059084,
 17017: 39.969202,
 17019: 40.13915,
 17021: 39.545524,
 17023: 39.332364,
 17025: 38.747312,
 17027: 38.606423,
 17029: 39.51368,
 17031: 41.894294,
 17033: 39.00373,
 17035: 39.273121,
 17037: 41.894612,
 17039: 40.181499,
 17041: 39.766078,
 17043: 41.852058,
 17045: 39.679037,
 17047: 38.417095,
 17049: 39.047694,
 17051: 39.001125,
 17053: 40.594423,
 17055: 37.991848,
 17057: 40.465688,
 17059: 37.768677,
 17061: 39.355444,
 17063: 41.29241,
 17065: 38.085226,
 17067: 40.405792,
 17069: 37.517852,
 17071: 40.815141,
 17073: 41.350021,
 17075: 40.748867,
 17077: 37.786096,
 17079: 39.004874,
 17081: 38.30078,
 17083: 39.080192,
 17085: 42.362391,
 17087: 37.460815,
 17089: 41.939594,
 17091: 41.139494,
 17093: 41.58814,
 17095: 40.930941,
 17097: 42.326444,
 17099: 41.343341,
 17101: 38.718954,
 17103: 41.747442,
 17105: 40.894376,
 17107: 40.12907,
 17109: 40.455789,
 17111: 42.324298,
 17113: 40.494559,
 17115: 39.860237,
 17117: 39.2659,
 17119: 38.827082,
 17121: 38.648396,
 17123: 41.031119,
 17125: 40.236993,
 17127: 37.216119,
 17129: 40.022569,
 17131: 41.204791,
 17133: 38.277983,
 17135: 39.228092,
 17137: 39.716806,
 17139: 39.636896,
 17141: 42.041884,
 17143: 40.785999,
 17145: 38.084385,
 17147: 40.009056,
 17149: 39.625106,
 17151: 37.417169,
 17153: 37.215615,
 17155: 41.19894,
 17157: 38.056515,
 17159: 38.71155,
 17161: 41.468404,
 17163: 38.470198,
 17165: 37.751653,
 17167: 39.756378,
 17169: 40.156905,
 17171: 39.636979,
 17173: 39.384926,
 17175: 41.096908,
 17177: 42.349726,
 17179: 40.508074,
 17181: 37.475104,
 17183: 40.18674,
 17185: 38.445821,
 17187: 40.850441,
 17189: 38.35314,
 17191: 38.431948,
 17193: 38.087372,
 17195: 41.750571,
 17197: 41.448474,
 17199: 37.730353,
 17201: 42.337396,
 17203: 40.789596,
 18001: 40.745733,
 18003: 41.091855,
 18005: 39.205843,
 18007: 40.608253,
 18009: 40.472672,
 18011: 40.050892,
 18013: 39.192585,
 18015: 40.58498,
 18017: 40.753799,
 18019: 38.476217,
 18021: 39.393951,
 18023: 40.305944,
 18025: 38.289433,
 18027: 38.696155,
 18029: 39.151491,
 18031: 39.30598,
 18033: 41.401189,
 18035: 40.227165,
 18037: 38.373344,
 18039: 41.600693,
 18041: 39.639655,
 18043: 38.317936,
 18045: 40.121282,
 18047: 39.409762,
 18049: 41.050384,
 18051: 38.317413,
 18053: 40.515758,
 18055: 39.0486,
 18057: 40.04987,
 18059: 39.822604,
 18061: 38.18644,
 18063: 39.768749,
 18065: 39.929576,
 18067: 40.483537,
 18069: 40.826394,
 18071: 38.911957,
 18073: 41.017688,
 18075: 40.434972,
 18077: 38.783604,
 18079: 38.996234,
 18081: 39.495986,
 18083: 38.688663,
 18085: 41.244293,
 18087: 41.642468,
 18089: 41.472239,
 18091: 41.549011,
 18093: 38.839815,
 18095: 40.166203,
 18097: 39.782976,
 18099: 41.325003,
 18101: 38.705322,
 18103: 40.772881,
 18105: 39.160751,
 18107: 40.040296,
 18109: 39.482646,
 18111: 40.962399,
 18113: 41.400794,
 18115: 38.940527,
 18117: 38.547381,
 18119: 39.317339,
 18121: 39.77425,
 18123: 38.081436,
 18125: 38.397898,
 18127: 41.509922,
 18129: 38.027614,
 18131: 41.045272,
 18133: 39.665544,
 18135: 40.164414,
 18137: 39.10023,
 18139: 39.622312,
 18141: 41.617699,
 18143: 38.679431,
 18145: 39.524135,
 18147: 38.009789,
 18149: 41.28322,
 18151: 41.643437,
 18153: 39.089225,
 18155: 38.825846,
 18157: 40.38926,
 18159: 40.310229,
 18161: 39.623111,
 18163: 38.02007,
 18165: 39.854045,
 18167: 39.429143,
 18169: 40.843717,
 18171: 40.352658,
 18173: 38.097764,
 18175: 38.600612,
 18177: 39.863091,
 18179: 40.735273,
 18181: 40.75095,
 18183: 41.136426,
 19001: 41.328528,
 19003: 41.021656,
 19005: 43.274964,
 19007: 40.744683,
 19009: 41.679178,
 19011: 42.092547,
 19013: 42.472888,
 19015: 42.038601,
 19017: 42.78089,
 19019: 42.470328,
 19021: 42.741522,
 19023: 42.734708,
 19025: 42.38617,
 19027: 42.039492,
 19029: 41.333824,
 19031: 41.772355,
 19033: 43.075171,
 19035: 42.742738,
 19037: 43.059741,
 19039: 41.029191,
 19041: 43.079822,
 19043: 42.840998,
 19045: 41.898073,
 19047: 42.043119,
 19049: 41.685321,
 19051: 40.748089,
 19053: 40.736379,
 19055: 42.473003,
 19057: 40.915339,
 19059: 43.389611,
 19061: 42.463481,
 19063: 43.377984,
 19065: 42.86445,
 19067: 43.052741,
 19069: 42.736549,
 19071: 40.743726,
 19073: 42.042494,
 19075: 42.403323,
 19077: 41.683573,
 19079: 42.390768,
 19081: 43.075411,
 19083: 42.389955,
 19085: 41.688584,
 19087: 40.985864,
 19089: 43.365312,
 19091: 42.782221,
 19093: 42.39186,
 19095: 41.683918,
 19097: 42.164281,
 19099: 41.685686,
 19101: 41.00688,
 19103: 41.668736,
 19105: 42.125118,
 19107: 41.331182,
 19109: 43.212478,
 19111: 40.647588,
 19113: 42.077951,
 19115: 41.218211,
 19117: 41.033344,
 19119: 43.38358,
 19121: 41.330622,
 19123: 41.330797,
 19125: 41.331455,
 19127: 42.041691,
 19129: 41.033703,
 19131: 43.348564,
 19133: 42.049432,
 19135: 41.028847,
 19137: 41.021735,
 19139: 41.483776,
 19141: 43.083746,
 19143: 43.378542,
 19145: 40.73909,
 19147: 43.075854,
 19149: 42.737585,
 19151: 42.734033,
 19153: 41.684281,
 19155: 41.340184,
 19157: 41.684526,
 19159: 40.735334,
 19161: 42.387526,
 19163: 41.641679,
 19165: 41.679014,
 19167: 43.082854,
 19169: 42.037538,
 19171: 42.074848,
 19173: 40.737949,
 19175: 41.02855,
 19177: 40.754117,
 19179: 41.031263,
 19181: 41.336769,
 19183: 41.329401,
 19185: 40.739983,
 19187: 42.434397,
 19189: 43.378124,
 19191: 43.292989,
 19193: 42.39322,
 19195: 43.373491,
 19197: 42.733007,
 20001: 37.884228,
 20003: 38.215114,
 20005: 39.532544,
 20007: 37.222906,
 20009: 38.481239,
 20011: 37.8561,
 20013: 39.825931,
 20015: 37.773681,
 20017: 38.298553,
 20019: 37.154259,
 20021: 37.169392,
 20023: 39.789256,
 20025: 37.233831,
 20027: 39.344964,
 20029: 39.487329,
 20031: 38.23645,
 20033: 37.189071,
 20035: 37.234507,
 20037: 37.505628,
 20039: 39.783542,
 20041: 38.867735,
 20043: 39.788502,
 20045: 38.896573,
 20047: 37.883595,
 20049: 37.456026,
 20051: 38.914596,
 20053: 38.700845,
 20055: 38.049855,
 20057: 37.688365,
 20059: 38.558019,
 20061: 39.002155,
 20063: 38.917239,
 20065: 39.349445,
 20067: 37.547537,
 20069: 37.744513,
 20071: 38.480408,
 20073: 37.878659,
 20075: 37.995244,
 20077: 37.188184,
 20079: 38.050144,
 20081: 37.55855,
 20083: 38.087493,
 20085: 39.410989,
 20087: 39.239644,
 20089: 39.77701,
 20091: 38.883907,
 20093: 37.994461,
 20095: 37.552951,
 20097: 37.561231,
 20099: 37.191468,
 20101: 38.481286,
 20103: 39.189511,
 20105: 39.047276,
 20107: 38.216549,
 20109: 38.913269,
 20111: 38.455498,
 20113: 38.395812,
 20115: 38.359647,
 20117: 39.782709,
 20119: 37.243886,
 20121: 38.566772,
 20123: 39.393026,
 20125: 37.189537,
 20127: 38.687696,
 20129: 37.185249,
 20131: 39.791043,
 20133: 37.564283,
 20135: 38.480437,
 20137: 39.783867,
 20139: 38.649706,
 20141: 39.348649,
 20143: 39.137963,
 20145: 38.182873,
 20147: 39.784506,
 20149: 39.382187,
 20151: 37.647594,
 20153: 39.786198,
 20155: 37.948185,
 20157: 39.82891,
 20159: 38.347178,
 20161: 39.291211,
 20163: 39.346006,
 20165: 38.523592,
 20167: 38.916839,
 20169: 38.786327,
 20171: 38.481877,
 20173: 37.683807,
 20175: 37.180585,
 20177: 39.041805,
 20179: 39.350542,
 20181: 39.351352,
 20183: 39.78466,
 20185: 38.03563,
 20187: 37.565932,
 20189: 37.202356,
 20191: 37.236663,
 20193: 39.357706,
 20195: 38.921302,
 20197: 38.955154,
 20199: 38.926626,
 20201: 39.776714,
 20203: 38.481922,
 20205: 37.558515,
 20207: 37.888484,
 20209: 39.115384,
 21001: 37.105541,
 21003: 36.75077,
 21005: 38.005396,
 21007: 37.05112,
 ...}

In [27]:
lat_dict[36998] = 40.7128

# Adding lat and long columns for center of county

In [69]:
def get_lon(fips):
    try:
        lon = lon_dict[fips]
    except:
        lon = np.NaN
    
    return lon

In [71]:
def get_lat(fips):
    try:
        lat = lat_dict[fips]
    except:
        lat = np.NaN
    return lat

In [22]:
df_covid = df_covid[df_covid['fips'] != 44999]

In [29]:
df_covid = df_covid[df_covid['fips'] != 34999]

In [31]:
df_covid = df_covid[df_covid['fips'] != 72999]

In [ ]:
df_covid = df_covid[df_covid['fips'] != 34999]

In [33]:
df_covid = df_covid[df_covid['fips'] != 78999]

In [35]:
df_covid = df_covid[df_covid['fips'] != 66999]

In [37]:
df_covid = df_covid[df_covid['fips'] != 25999]

In [39]:
df_covid = df_covid[df_covid['fips'] != 23999]

In [41]:
df_covid = df_covid[df_covid['fips'] != 22999]

In [43]:
df_covid = df_covid[df_covid['fips'] != 47999]

In [45]:
df_covid = df_covid[df_covid['fips'] != 32999]

In [47]:
df_covid = df_covid[df_covid['fips'] != 21999]

In [49]:
df_covid = df_covid[df_covid['fips'] != 29999]

In [51]:
df_covid = df_covid[df_covid['fips'] != 29998]

In [53]:
df_covid = df_covid[df_covid['fips'] != 13999]

In [55]:
df_covid = df_covid[df_covid['fips'] != 5999]

In [57]:
df_covid = df_covid[df_covid['fips'] != 27999]

In [59]:
df_covid = df_covid[df_covid['fips'] != 12999]

In [61]:
df_covid = df_covid[df_covid['fips'] != 8999]

In [63]:
df_covid = df_covid[df_covid['fips'] != 6999]

In [70]:
df_covid['lon'] = df_covid['fips'].apply(lambda x: get_lon(x))

In [72]:
df_covid['lat'] = df_covid['fips'].apply(lambda x: get_lat(x))

In [73]:
df_covid.value_counts()

date        geoid      county      state       cases  cases_avg  cases_avg_per_100k  deaths  deaths_avg  deaths_avg_per_100k  fips   lon          lat
2020-01-21  USA-53061  Snohomish   Washington  1      0.14       0.02                0       0.00        0.00                 53061  -121.766412  48.054913    1
2021-04-01  USA-19093  Ida         Iowa        1      1.33       19.44               0       0.00        0.00                 19093  -95.507421   42.391860    1
            USA-18013  Brown       Indiana     0      1.00       6.63                0       0.00        0.00                 18013  -86.239410   39.192585    1
            USA-18011  Boone       Indiana     6      8.14       12.00               0       0.29        0.42                 18011  -86.469014   40.050892    1
            USA-18009  Blackford   Indiana     3      2.43       20.65               0       0.00        0.00                 18009  -85.323730   40.472672    1
                                                                                                                                                              ..
2020-10-01  USA-23011  Kennebec    Maine       6      1.71       1.40                0       0.00        0.00                 23011  -69.765764   44.417012    1
            USA-23009  Hancock     Maine       0      0.14       0.26                0       0.00        0.00                 23009  -68.370703   44.564906    1
            USA-23007  Franklin    Maine       0      0.50       1.66                0       0.00        0.00                 23007  -70.444727   44.973012    1
            USA-23005  Cumberland  Maine       1      4.57       1.55                0       0.00        0.00                 23005  -70.330375   43.808348    1
2021-09-29  USA-56045  Weston      Wyoming     6      5.29       76.31               0       0.00        0.00                 56045  -104.570020  43.846213    1
Length: 1707999, dtype: int64

In [78]:
df_covid = df_covid.dropna()

In [80]:
df_covid.shape

(1707999, 13)

In [81]:
df_covid.head()

,date,geoid,county,state,cases,cases_avg,cases_avg_per_100k,deaths,deaths_avg,deaths_avg_per_100k,fips,lon,lat
0,2020-01-21,USA-53061,Snohomish,Washington,1,0.14,0.02,0,0.0,0.0,53061,-121.766412,48.054913
1,2020-01-22,USA-53061,Snohomish,Washington,0,0.14,0.02,0,0.0,0.0,53061,-121.766412,48.054913
2,2020-01-23,USA-53061,Snohomish,Washington,0,0.14,0.02,0,0.0,0.0,53061,-121.766412,48.054913
3,2020-01-24,USA-53061,Snohomish,Washington,0,0.14,0.02,0,0.0,0.0,53061,-121.766412,48.054913
4,2020-01-24,USA-17031,Cook,Illinois,1,0.14,0.00,0,0.0,0.0,17031,-87.645455,41.894294

In [82]:
df_scatter_clean = df_covid[['date', 'county', 'state', 'fips', 'lon' , 'lat', 'cases_avg_per_100k']]

In [87]:
df_scatter_clean

KeyboardInterrupt:

In [84]:
df_scatter_clean.to_csv("df_scatter_clean.csv")